# Generated by Django 4.2.11 on 2025-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titlu (opțional)')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Imagine')),
                ('active', models.BooleanField(default=True, verbose_name='Activ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Imagine slider',
                'verbose_name_plural': 'Imagini slider',
                'ordering': ['order'],
            },
        ),
    ]
